language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
python:
  - "3.6"
  - "3.7"
  - "3.8"
matrix:
  include:
    - python: 3.8
      env: TOXENV=precommit

install:
  - pip install tox tox-travis
script:
  - tox

before_deploy:
  - pip install poetry

deploy:
  - provider: script
    skip_cleanup: true
    script: poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
    on:
      all_branches: true
      condition: $TOXENV != precommit
      python: 3.8
      repo: jmaroeder/python-singletons
      tags: true
